name: check formatting

on:
  pull_request:

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: '.'
        exclude: './src/dependencies'
        clangFormatVersion: 11
        style: llvm
