name: CI

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: './src'
        exclude: './src/dependencies'
        extensions: 'h,cpp'
        clangFormatVersion: 11
        style: llvm
