name: Linux build

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: install ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: install dependencies
        run: make install-dependencies

      - name: build
        run: make build
