name: windows test

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: install ninja
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: install dependencies
        run: sudo make install-dependencies

      - name: test
        run: make test
